### ISSUE TITLE
Use more MIDI instruments

### ISSUE THREAD

**Issue by surikov** [haszari/kytaime#2]
Use hundreds of instruments, see example at
https://surikov.github.io/midi-sounds-react-examples/examples/midi-sounds-example10/build/

**Comment by haszari** [comment]
Your projects look interesting, thanks for getting in touch!

Can you provide a bit more detail about what changes you'd like to see in this project?

**Comment by haszari** [comment]
Closing this issue – this project is not focused on providing synthesis or instrumentation (other than sample playback).
